# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: d8d9e28f60adb7431d03d6a9f665c691203b131fc65eccf3c561ea48fc9e290600a5aa6ab845d3df1e3c930fd5ea5c9ac832890267362d4d6e49db3f91314286

test:
  secret_key_base: 834765622861c0ed5afb2d0034821ea775e46dee1f310509ae9f73ede15b79fed77c5d78836c420b3a826904ab34dfbdba818bcc67daa0a04fd38aad381b3293

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
